# Travis CI configuration
# Simply tests that Home Assistant configuration is valid.
# @link https://home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing

language: python

#hass uses 3.8.6
python:
  - 3.8.6
  - 3.9.0
  
before_install:
  - mv travis_secrets.yaml secrets.yaml
  
install:
  - pip3 install homeassistant
  
script:
  - hass -c . --script check_config
