resources:
#HACS#
  - url: /local/community/compact-custom-header/compact-custom-header.js
    type: module
  - url: /local/community/weather-card/weather-card.js
    type: module
  - url: /local/community/mini-media-player/mini-media-player.js
    type: module
  - url: /local/community/upcoming-media-card/upcoming-media-card.js
    type: js    
  - url: /local/community/simple-thermostat/simple-thermostat.js
    type: module
  - url: /local/community/atomic_calendar/atomic-calendar.js
    type: module 
  - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /local/community/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /local/community/lovelace-card-mod/card-mod.js
    type: module
  - url: /local/community/button-entity-row/button-entity-row.js
    type: js
  - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/community/light-entity-row/light-entity-row.js
    type: js
#LOCAL#    
  - url: /local/custom_ui/floorplan/floorplan-card.js?v=1.1.14
    type: module 
  - url: /local/custom_ui/column-card.js
    type: js
  - url: /local/custom_ui/layout-card.js
    type: js
  - url: /local/custom_ui/battery-entity.js?v=0.1
    type: module
  - url: /local/custom_ui/card-tools.js
    type: js
  - url: /local/custom_ui/custom-fan-card.js
    type: js
title: !secret name

cch:
  swipe: true
  swipe_amount: 15
  swipe_animate: none #none/swipe/fade/flip
  swipe_wrap: true
  swipe_prevent_default: false #stop default swipe action on device_tracker
  menu: overflow
  notifications: overflow
  voice: hide
  options: clock
  clock_format: 12
  clock_am_pm: false
  default_tab: 0
  clock_date: false
  exceptions:
    - conditions:
        user: !secret user2
      config:
        hide_tabs: 4,5,7,8
    - conditions:
        user: !secret user3
      config:           
        hide_tabs: 3,4
        
views: !include_dir_list ui-lovelace/