resources:
#HACS#
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /local/community/weather-card/weather-card.js
    type: module
  - url: /local/community/mini-media-player/mini-media-player.js
    type: module
  - url: /local/community/upcoming-media-card/upcoming-media-card.js
    type: js    
  - url: /local/community/simple-thermostat/simple-thermostat.js
    type: module
  - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /local/community/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /local/community/lovelace-card-mod/card-mod.js
    type: module
  - url: /local/community/button-entity-row/button-entity-row.js
    type: module
  - url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/community/light-entity-row/light-entity-row.js
    type: js
  - url: /hacsfiles/garbage-collection-card/garbage-collection-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /local/commmunity/lovelace-layout-card/layout-card.js
    type: module
#LOCAL#    
  - url: /local/custom_ui/column-card.js
    type: js
  - url: /local/custom_ui/card-tools.js
    type: js
  - url: /local/custom_ui/custom-fan-card.js
    type: js
title: !secret name

custom_header:
  compact_mode: true
  default_tab: 0
  exceptions:
    - conditions:
        user: !secret user2
      config:
        hide_tabs: 4,5,7,8
    - conditions:
        user: !secret user3
      config:           
        hide_tabs: 3,4
    - conditions:
        user: !secret user4
      config:
        hide_tabs: 3,4,5,6,7,8
        
views: !include_dir_list ui-lovelace/