- alias: 'Turn On Humidifier When Fan is On'
  id: 'humidifier_on'
  trigger:
    - platform: state
      entity_id: switch.bedroom_fan
      to: 'on'
  action:
    - service: fan.turn_on 
      entity_id: fan.bedroom_humidifier

- alias: 'Turn Off Humidifier When Fan is Off'
  id: 'humidifier_off'
  trigger:
    - platform: state
      entity_id: switch.bedroom_fan
      to: 'off'
  action:
    - service: fan.turn_off 
      entity_id: fan.bedroom_humidifier

