- platform: sonarr
  api_key: !secret sonarr_api_key
  host: !secret unjoe_ip
  port: 8989
  days: 2
  monitored_conditions:
   - upcoming
   - wanted
   - queue

- platform: radarr
  api_key: !secret radarr_api_key
  host: !secret unjoe_ip
  port: 7878
  urlbase: /radarr
  monitored_conditions:
  -  movies
  -  upcoming
  days: 7
   
#- platform: nzbget
#  host: !secret unjoe_ip
#  port: 6789
#  name: NZBGet
#  username: !secret joe_user
#  password: !secret nzbget_password
#  monitored_variables:
#   - average_download_rate
#   - download_rate
#   - download_size
#   - remaining_size
#   - uptime 
#   - post_paused
#   - download_paused
#   - article_cache
  

