# - platform: mqtt_room
  # device_id: "eb8ee9fd-a49c-428f-829b-4553e34616e5"
  # away_timeout: 60
  # name: 'Office Sensor'
  # state_topic: room_presence
  
# - platform: mqtt_room
  # device_id: "mqttjs_a2a112e4"
  # away_timeout: 60
  # name: !secret roommate_mqtt
  # state_topic: room_presence
  
# - platform: mqtt_room
  # device_id: "e516f1d5-9fb4-4687-84ec-627e4d49f00d"
  # away_timeout: 60
  # name: 'Kitchen Sensor'
  # state_topic: room_presence
  
- platform: mqtt
  name: 'Office Camera Motion'
  state_topic: 'camera/motion/OfficeCamera'
  
- platform: mqtt
  name: 'Kitchen Camera Motion'
  state_topic: 'camera/motion/KitchenCamera'
  
- platform: mqtt
  name: 'Backyard Camera Motion'
  state_topic: 'camera/motion/BackyardCamera'
  
- platform: mqtt
  name: 'Driveway Camera Motion'
  state_topic: 'camera/motion/DrivewayCamera'

- platform: mqtt
  name: 'Front Room Camera Camera Motion'
  state_topic: 'camera/motion/FrontRoomCamera'
  
- platform: mqtt
  name: 'Pool Camera Motion'
  state_topic: 'camera/motion/PoolCamera'
  
- platform: mqtt
  name: 'Street Camera Motion'
  state_topic: 'camera/motion/StreetCamera'

- platform: mqtt
  name: 'Living Room Camera Motion'
  state_topic: 'camera/motion/LivingRoomCamera'