- platform: template
  sensors:
    theater_volume:
      value_template: >
        {% if is_state('media_player.theatre_room_main', 'off') %}
          0
        {% else %}
          {{ (( states.media_player.theatre_room_main.attributes.volume_level | float*100 ) | round(0) ) | int }}
        {% endif %}
      
    living_room_volume:
      value_template: >
        {% if is_state('media_player.living_room_main', 'off') %}
          0
        {% else %}
          {{ (( states.media_player.living_room_main.attributes.volume_level | float*100 ) | round(0) ) | int }}
        {% endif %} 
      
    living_room_z2_volume: 
      value_template: >
        {% if is_state('media_player.living_room_zone2', 'off') %}
          0
        {% else %}
          {{ (( states.media_player.living_room_zone2.attributes.volume_level | float*100 ) | round(0) ) | int }}
        {% endif %} 