- platform: radarr_upcoming_media
  api_key: !secret radarr_api_key
  host: !secret unjoe_ip
  port: 7878
  days: 120
  ssl: false
  theaters: false
  max: 10
  urlbase: /radarr
  
- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret unjoe_ip
  port: 8989
  days: 5
  ssl: false
  max: 10
  urlbase: /sonarr
  
- platform: plex_recently_added
  token: !secret plex_token
  host: !secret unjoe_ip
  port: 32400
  ssl: false
  ssl_cert: false
  download_images: true
  max: 5
  section_types:
  - movie
  - show