- platform: ring

- platform: iss

# - platform: template
  # sensors:
    # pantry_open:
      # friendly_name: "Pantry Door Status"
      # value_template: >-
        # {{ is_state('binary_sensor.pantry_door', 'Open') }}
      # icon_template: >-
        # {% if is_state("binary_sensor.pantry_door", "on") %}
          # mdi:door-open
        # {% else %}
          # mdi:door-closed
        # {% endif %}
        