- platform: deepstack_face
  ip_address: !secret unjoe_ip
  port: 5000
  api_key: !secret deepstack_api
  timeout: 10
  detect_only: True
  scan_interval: 20
  source:
    - entity_id: camera.uvc_g3_dome_living_room
      name: Living Room Faces